services:
  app:
    environment: 
      DJANGO_SETTINGS_MODULE: mlarchive.settings.settings
      SECRET_KEY: 2y&2u=%@di1tnc3gt82e9p@$7cq7nbctll41d02@e$#=9jrzj$
      DATABASES_PASSWORD: franticmarble
      DATABASES_HOST: db
      ELASTICSEARCH_HOST: es

    build:
      context: .
      dockerfile: docker/app.Dockerfile

    init: true

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db

    depends_on:
      - db
      - es
      - rabbit

    ipc: host
    volumes:
      - app-data:/data
      - app-assets:/assets

  es:
    image: "elasticsearch:7.17.21"
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=changeme
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: "kibana:7.17.21"
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD:-changeme}
      - XPACK_SECURITY_ENABLED=true
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${KIBANA_ENCRYPTION_KEY:-min-32-byte-long-strong-encryption-key}
      - SERVER_PUBLICBASEURL=http://localhost:5601
    depends_on:
      - es

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: mailarch
      POSTGRES_USER: mailarch
      POSTGRES_PASSWORD: franticmarble
      POSTGRES_HOST_AUTH_METHOD: trust
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
      - app-assets:/assets

  rabbit:
    image: rabbitmq:3.12-alpine
    restart: always
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  celery:
    build:
      context: .
      dockerfile: build/app/Dockerfile
    init: true
    environment:
      CELERY_APP: mlarchive.celeryapp:app
      CONTAINER_ROLE: celery
      UPDATE_REQUIREMENTS_FROM: requirements.txt
      BROKER_URL: amqp://guest:guest@rabbit:5672//
      DJANGO_SETTINGS_MODULE: mlarchive.settings.settings
      SECRET_KEY: 2y&2u=%@di1tnc3gt82e9p@$7cq7nbctll41d02@e$#=9jrzj$
      DATABASES_PASSWORD: franticmarble
      DATABASES_HOST: db
      ELASTICSEARCH_HOST: es
    depends_on:
      - app
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
      - app-data:/data
      - app-assets:/assets

  beat:
    build:
      context: .
      dockerfile: build/app/Dockerfile
    init: true
    environment:
      CELERY_APP: mlarchive.celeryapp:app
      CONTAINER_ROLE: beat
      UPDATE_REQUIREMENTS_FROM: requirements.txt
      BROKER_URL: amqp://guest:guest@rabbit:5672//
      DJANGO_SETTINGS_MODULE: mlarchive.settings.settings
      SECRET_KEY: 2y&2u=%@di1tnc3gt82e9p@$7cq7nbctll41d02@e$#=9jrzj$
      DATABASES_PASSWORD: franticmarble
      DATABASES_HOST: db
      ELASTICSEARCH_HOST: es
    # depends on /data subdirectories
    depends_on:
      - app
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
      - app-data:/data
      - app-assets:/assets

volumes:
    app-assets:
    app-data:
    postgresdb-data:
    es-data:
