# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_set_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_index_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='thread_index_page',
            field=models.IntegerField(default=0),
        ),
    ]
