# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_set_on_delete'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=[b'email_list', b'date'], name='archive_mes_email_l_6e307c_idx'),
        ),
    ]
