# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 19:48
from __future__ import unicode_literals

from django.db import migrations


def set_email_list(apps, schema_editor):
    '''Traverse all message records, read in_reply_to_value and
    populate in_reply_to FK'''
    Thread = apps.get_model("archive", "Thread")
    for thread in Thread.objects.all():
        thread.email_list = thread.first.email_list
        thread.save() 


def reverse_set_email_list(apps, schema_editor):
    Thread = apps.get_model("archive", "Thread")
    for thread in Thread.objects.all():
        thread.email_list = None
        thread.save() 


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_thread_email_list'),
    ]

    operations = [
        migrations.RunPython(set_email_list, reverse_set_email_list),
    ]
