# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-24 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_auto_20180724_2249'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE archive_message MODIFY frm VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;",
            "ALTER TABLE archive_message MODIFY frm VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;",
        ),
        migrations.RunSQL(
            "ALTER TABLE archive_message MODIFY subject VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;",
            "ALTER TABLE archive_message MODIFY subject VARCHAR(512) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;",
        ),
        migrations.RunSQL(
            "ALTER TABLE archive_message MODIFY base_subject VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;",
            "ALTER TABLE archive_message MODIFY base_subject VARCHAR(512) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;",
        )
    ]
