# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0017_auto_20180725_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='content_disposition',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='content_type',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
