apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: celery
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: celery
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - mailarchive
              topologyKey: "kubernetes.io/hostname"
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
      containers:
        # -----------------------------------------------------
        # Celery Container
        # -----------------------------------------------------
        - name: celery
          image: "ghcr.io/ietf-tools/mailarchive:$APP_IMAGE_TAG"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          volumeMounts:
            - name: ml-vol
              mountPath: /mnt/mailarchive
            - name: ml-tmp
              mountPath: /tmp
          env:
            - name: "CONTAINER_ROLE"
              value: "celery"
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: ml-secrets-env
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
        # -----------------------------------------------------
        # ScoutAPM Container
        # -----------------------------------------------------
        - name: scoutapm
          image: "scoutapp/scoutapm:version-1.4.0"
          imagePullPolicy: IfNotPresent
          # Replace command with one that will shut down on a TERM signal
          # The ./core-agent start command line is from the scoutapm docker image
          command:
            - "sh"
            - "-c"
            - >-
              trap './core-agent shutdown --tcp 0.0.0.0:6590' TERM;
              ./core-agent start --daemonize false --log-level warn --tcp 0.0.0.0:6590 &
              wait $!
          livenessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "./core-agent probe --tcp 0.0.0.0:6590 | grep -q 'Agent found'"
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 65534 # "nobody" user by default
            runAsGroup: 65534  # "nogroup" group by default
      volumes:
        # To be overriden with the actual shared volume
        - name: ml-vol
        - name: ml-tmp
          emptyDir:
            sizeLimit: "2Gi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30