# Generated by Django 5.2.13 on 2026-06-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blobdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='checksum',
            field=models.CharField(db_index=True, editable=False, help_text='SHA-384 digest of the content', max_length=96),
        ),
    ]
