# Generated by Django 4.1.3 on 2023-01-17 15:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('alias', models.CharField(blank=True, max_length=65)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('members_digest', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(db_index=True, max_length=65, unique=True)),
                ('private', models.BooleanField(db_index=True, default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Legacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_list_id', models.CharField(max_length=40)),
                ('msgid', models.CharField(db_index=True, max_length=240)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_subject', models.CharField(blank=True, db_index=True, max_length=512)),
                ('cc', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField(db_index=True)),
                ('frm', models.CharField(blank=True, db_index=True, max_length=255)),
                ('from_line', models.CharField(blank=True, max_length=255)),
                ('hashcode', models.CharField(db_index=True, max_length=28)),
                ('in_reply_to_value', models.TextField(blank=True, default='')),
                ('legacy_number', models.IntegerField(blank=True, db_index=True, null=True)),
                ('msgid', models.CharField(db_index=True, max_length=240)),
                ('references', models.TextField(blank=True, default='')),
                ('spam_score', models.IntegerField(default=0)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('thread_depth', models.IntegerField(default=0)),
                ('thread_order', models.IntegerField(default=0)),
                ('to', models.TextField(blank=True, default='')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('email_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.emaillist')),
                ('in_reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='archive.message')),
            ],
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old', models.CharField(db_index=True, max_length=255, unique=True)),
                ('new', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True)),
                ('email_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.emaillist')),
                ('first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_key', to='archive.message')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('count', models.PositiveIntegerField()),
                ('email_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.emaillist')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.thread'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('filename', models.CharField(blank=True, default='', max_length=65)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=150)),
                ('content_disposition', models.CharField(blank=True, max_length=150, null=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.message')),
            ],
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['email_list', 'date'], name='archive_mes_email_l_6e307c_idx'),
        ),
    ]
