# Generated by Django 3.2.7 on 2021-10-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='base_subject',
            field=models.CharField(blank=True, db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='message',
            name='frm',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
