# Generated by Django 4.2.7 on 2023-11-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="msgid",
            field=models.CharField(db_index=True, max_length=998),
        ),
    ]
