# Generated by Django 4.1.2 on 2022-10-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0002_auto_20211028_1444"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillist",
            name="members_digest",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
