# Generated by Django 4.1.2 on 2022-12-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0003_alter_emaillist_members_digest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("count", models.PositiveIntegerField()),
                (
                    "email_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="archive.emaillist",
                    ),
                ),
            ],
        ),
    ]
