# Generated by Django 4.2.20 on 2025-05-27 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("archive", "0003_fix_message_msgid"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailmanMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="UserEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["email_list", "frm"], name="archive_mes_email_l_f73af8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["email_list", "base_subject"],
                name="archive_mes_email_l_4718c4_idx",
            ),
        ),
        migrations.AddField(
            model_name="useremail",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="mailmanmember",
            name="email_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="archive.emaillist"
            ),
        ),
    ]
