# Generated by Django 4.2.20 on 2025-05-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0003_fix_message_msgid"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["email_list", "frm"], name="archive_mes_email_l_f73af8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["email_list", "base_subject"],
                name="archive_mes_email_l_4718c4_idx",
            ),
        ),
    ]
