# Generated by Django 4.1.2 on 2022-10-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0003_alter_emaillist_members_digest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old", models.CharField(db_index=True, max_length=255)),
                ("new", models.CharField(max_length=255)),
            ],
        ),
    ]
