# Generated by Django 4.2.20 on 2025-04-27 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0003_fix_message_msgid"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE archive_thread
            DROP CONSTRAINT archive_thread_first_id_6d9b9407_fk_archive_message_id;

            ALTER TABLE archive_thread
            ADD CONSTRAINT archive_thread_first_id_6d9b9407_fk_archive_message_id
            FOREIGN KEY (first_id)
            REFERENCES archive_message (id)
            ON DELETE SET NULL;

            ALTER TABLE archive_thread
            DROP CONSTRAINT archive_thread_email_list_id_bbea794e_fk_archive_emaillist_id;

            ALTER TABLE archive_thread
            ADD CONSTRAINT archive_thread_email_list_id_bbea794e_fk_archive_emaillist_id
            FOREIGN KEY (email_list_id)
            REFERENCES archive_emaillist (id)
            ON DELETE CASCADE;

            ALTER TABLE archive_message
            DROP CONSTRAINT archive_message_email_list_id_20e34f25_fk_archive_emaillist_id;

            ALTER TABLE archive_message
            ADD CONSTRAINT archive_message_email_list_id_20e34f25_fk_archive_emaillist_id
            FOREIGN KEY (email_list_id)
            REFERENCES archive_emaillist (id)
            ON DELETE RESTRICT;

            ALTER TABLE archive_message
            DROP CONSTRAINT archive_message_in_reply_to_id_2a3003e0_fk_archive_message_id;

            ALTER TABLE archive_message
            ADD CONSTRAINT archive_message_in_reply_to_id_2a3003e0_fk_archive_message_id
            FOREIGN KEY (in_reply_to_id)
            REFERENCES archive_message (id)
            ON DELETE SET NULL;

            ALTER TABLE archive_message
            DROP CONSTRAINT archive_message_thread_id_842ee020_fk_archive_thread_id;

            ALTER TABLE archive_message
            ADD CONSTRAINT archive_message_thread_id_842ee020_fk_archive_thread_id
            FOREIGN KEY (thread_id)
            REFERENCES archive_thread (id)
            ON DELETE RESTRICT;

            ALTER TABLE archive_attachment
            DROP CONSTRAINT archive_attachment_message_id_839391cb_fk_archive_message_id;

            ALTER TABLE archive_attachment
            ADD CONSTRAINT archive_attachment_message_id_839391cb_fk_archive_message_id
            FOREIGN KEY (message_id)
            REFERENCES archive_message (id)
            ON DELETE CASCADE;

            ALTER TABLE archive_subscriber
            DROP CONSTRAINT archive_subscriber_email_list_id_d4f15f5e_fk_archive_e;

            ALTER TABLE archive_subscriber
            ADD CONSTRAINT archive_subscriber_email_list_id_d4f15f5e_fk_archive_e
            FOREIGN KEY (email_list_id)
            REFERENCES archive_emaillist (id)
            ON DELETE RESTRICT;
            """,
            reverse_sql="""
            ALTER TABLE archive_thread
            DROP CONSTRAINT archive_thread_first_id_6d9b9407_fk_archive_message_id;

            ALTER TABLE archive_thread
            ADD CONSTRAINT archive_thread_first_id_6d9b9407_fk_archive_message_id
            FOREIGN KEY (first_id)
            REFERENCES archive_message (id)
            ON DELETE NO ACTION;

            ALTER TABLE archive_thread
            DROP CONSTRAINT archive_thread_email_list_id_bbea794e_fk_archive_emaillist_id;

            ALTER TABLE archive_thread
            ADD CONSTRAINT archive_thread_email_list_id_bbea794e_fk_archive_emaillist_id
            FOREIGN KEY (email_list_id)
            REFERENCES archive_emaillist (id)
            ON DELETE NO ACTION;

            ALTER TABLE archive_message
            DROP CONSTRAINT archive_message_email_list_id_20e34f25_fk_archive_emaillist_id;

            ALTER TABLE archive_message
            ADD CONSTRAINT archive_message_email_list_id_20e34f25_fk_archive_emaillist_id
            FOREIGN KEY (email_list_id)
            REFERENCES archive_emaillist (id)
            ON DELETE NO ACTION;

            ALTER TABLE archive_message
            DROP CONSTRAINT archive_message_in_reply_to_id_2a3003e0_fk_archive_message_id;

            ALTER TABLE archive_message
            ADD CONSTRAINT archive_message_in_reply_to_id_2a3003e0_fk_archive_message_id
            FOREIGN KEY (in_reply_to_id)
            REFERENCES archive_message (id)
            ON DELETE NO ACTION;

            ALTER TABLE archive_message
            DROP CONSTRAINT archive_message_thread_id_842ee020_fk_archive_thread_id;

            ALTER TABLE archive_message
            ADD CONSTRAINT archive_message_thread_id_842ee020_fk_archive_thread_id
            FOREIGN KEY (thread_id)
            REFERENCES archive_thread (id)
            ON DELETE NO ACTION;

            ALTER TABLE archive_attachment
            DROP CONSTRAINT archive_attachment_message_id_839391cb_fk_archive_message_id;

            ALTER TABLE archive_attachment
            ADD CONSTRAINT archive_attachment_message_id_839391cb_fk_archive_message_id
            FOREIGN KEY (message_id)
            REFERENCES archive_message (id)
            ON DELETE NO ACTION;

            ALTER TABLE archive_subscriber
            DROP CONSTRAINT archive_subscriber_email_list_id_d4f15f5e_fk_archive_e;

            ALTER TABLE archive_subscriber
            ADD CONSTRAINT archive_subscriber_email_list_id_d4f15f5e_fk_archive_e
            FOREIGN KEY (email_list_id)
            REFERENCES archive_emaillist (id)
            ON DELETE NO ACTION;
            """
        ),

    ]
