# Generated by Django 5.2.7 on 2025-10-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_mailmanmember_useremail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=1024)),
                ('sha384', models.CharField(max_length=96)),
                ('len', models.PositiveBigIntegerField()),
                ('store_created', models.DateTimeField(help_text='The instant the object ws first placed in the store')),
                ('created', models.DateTimeField(help_text="Instant object became known. May not be the same as the storage's created value for the instance. It will hold ctime for objects imported from older disk storage")),
                ('modified', models.DateTimeField(help_text="Last instant object was modified. May not be the same as the storage's modified value for the instance. It will hold mtime for objects imported from older disk storage unless they've actually been overwritten more recently")),
                ('deleted', models.DateTimeField(null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'name'), name='unique_name_per_store')],
            },
        ),
    ]
