# Generated by Django 5.2.17 on 2026-08-14 22:55

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # build the index without locking archive_thread against writes,
    # which requires running outside a transaction
    atomic = False

    dependencies = [
        ('archive', '0004_mailmanmember_useremail_and_more'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='thread',
            index=models.Index(fields=['email_list', 'date'], name='archive_thr_email_l_593979_idx'),
        ),
    ]
