# Generated by Django 4.2.20 on 2025-05-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0004_message_archive_mes_email_l_f73af8_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="thread_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
