# Generated by Django 4.1.2 on 2022-12-12 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0004_subscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
