# Generated by Django 5.2.17 on 2026-08-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_thread_archive_thr_email_l_593979_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(help_text='Name of the store holding this object', max_length=256)),
                ('name', models.CharField(help_text='Name of the object within the store', max_length=1024)),
                ('sha384', models.CharField(help_text='SHA-384 digest of the content', max_length=96)),
                ('len', models.PositiveBigIntegerField(help_text='Length of the content in bytes')),
                ('content_type', models.CharField(blank=True, help_text='content-type header value for the object contents', max_length=1024)),
                ('mtime', models.DateTimeField(blank=True, default=None, help_text='mtime associated with the object as a filesystem object', null=True)),
                ('store_created', models.DateTimeField(help_text='The instant the object was first placed in the store')),
                ('created', models.DateTimeField(help_text="Instant object became known. May not be the same as the storage's created value for the instance. It will hold ctime for objects imported from older disk storage")),
                ('modified', models.DateTimeField(help_text="Last instant object was modified. May not be the same as the storage's modified value for the instance. It will hold mtime for objects imported from older disk storage unless they have actually been overwritten more recently")),
                ('deleted', models.DateTimeField(default=None, help_text='Instant the object was removed from the store. Because (store, name) is unique this is a current-state flag, not a delete history: storing the same name again clears it', null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'modified'], name='archive_sto_store_4add05_idx'), models.Index(fields=['sha384'], name='archive_sto_sha384_d550b8_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'name'), name='unique_name_per_store')],
            },
        ),
    ]
