# Generated by Django 5.2.17 on 2026-09-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_storedobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedobject',
            name='name',
            field=models.CharField(db_collation='C', max_length=1024),
        ),
    ]
