# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 19:34


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_add_db_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='email_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.EmailList'),
        ),
    ]
