# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 19:48


from django.db import migrations


def set_email_list(apps, schema_editor):
    '''Traverse all threads and populate email_list field'''
    # first delete empty threads
    Thread = apps.get_model("archive", "Thread")
    for thread in Thread.objects.all():
        if thread.first:
            thread.email_list = thread.first.email_list
            thread.save()
        else:
            if thread.message_set.count() > 0:
                first = thread.message_set.order_by('date').first()
                thread.first = first
                thread.email_list = thread.first.email_list
                thread.save()
            else:
                thread.delete()


def reverse_set_email_list(apps, schema_editor):
    Thread = apps.get_model("archive", "Thread")
    for thread in Thread.objects.all():
        thread.email_list = None
        thread.save() 


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_thread_email_list'),
    ]

    operations = [
        migrations.RunPython(set_email_list, reverse_set_email_list),
    ]
