# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-13 15:21


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_populate_email_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
