# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0018_auto_20180802_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
