# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 11:13


from django.db import migrations


def process_attachments(apps, schema_editor):
    Attachment = apps.get_model("archive", "Attachment")

    for attachment in Attachment.objects.all():
        if '\n' in attachment.name or '\r' in attachment.name:
            attachment.name = attachment.name.replace('\r', '').replace('\n', '')
            attachment.save()
            print('Fixed {}: {}'.format(attachment.pk, attachment.name))


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0021_auto_20180824_1012'),
    ]

    operations = [
        migrations.RunPython(process_attachments),
    ]
