# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 13:46


from django.db import migrations


def process_attachments(apps, schema_editor):
    Attachment = apps.get_model("archive", "Attachment")
    Attachment.objects.filter(content_type='message/rfc822').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0022_fix_folded_filenames'),
    ]

    operations = [
        migrations.RunPython(process_attachments),
    ]
