# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-11 12:01


from django.contrib.sites.models import Site
from django.db import migrations


def configure_site(apps, schema_editor):
    site = Site.objects.get(id=1)
    site.domain = 'mailarchive.ietf.org'
    site.name = 'mailarchive.ietf.org'
    site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0023_remove_rfc822_attachments'),
    ]

    operations = [
        migrations.RunPython(configure_site),
    ]
