# Generated by Django 2.2.6 on 2020-01-17 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0024_auto_20190311_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Message'),
        ),
        migrations.AlterField(
            model_name='legacy',
            name='msgid',
            field=models.CharField(db_index=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='message',
            name='cc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='in_reply_to_value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='references',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='to',
            field=models.TextField(blank=True, default=''),
        ),
    ]
